spring:
  application:
    name: gateway-service
  config:
    import:
      - classpath:eureka-client-disabled.yml
      - classpath:springdoc-enabled.yml
  cloud:
    gateway:
      routes:
        - id: order-service # 주문 서비스가 있다고 가정 (현재 프로젝트에는 개설하지 않음)
          uri: http://localhost:8090
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1 # replenishRate는 사용자가 일정 시간 동안(보통 초 단위) 발생시킬 수 있는 요청의 수를 정의
            redis-rate-limiter.burstCapacity: 5 # burstCapacity는 토큰 버킷이 담을 수 있는 최대 토큰의 수를 정의
            key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      port: 6379
      host: 127.0.0.1

server:
  port: 8080

security:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMLOPQRTTTTTTTTT